name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/setup@v3

      - name: Use Node.js 26.x
        uses: actions/setup-node@v7
        with:
          node-version: 26.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Biome CI
        run: pnpm biome ci .

      - name: Type Check
        run: pnpm tsc --noEmit

      - name: Build
        run: pnpm run build
